version: '3.8'
services:
  api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diboas
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
volumes:
  postgres_data: